name: Deploy sample app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Aspire
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Azure login
      uses: azure/login@v2
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID}}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
    
    - name: Install Aspire CLI
      run: |
        echo "Installing Aspire CLI from install script..."
        curl -sSL https://aspire.dev/install.sh | bash
    
    - name: Verify Aspire CLI installation
      run: |
        which aspire
        aspire --version
    
    - name: Deploy with Aspire
      env:
        Azure__SubscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
        Azure__Location: ${{ secrets.AZURE_LOCATION }}
        Azure__ResourceGroup: ${{ secrets.AZURE_RESOURCEGROUP }}
        Azure__AllowResourceGroupCreation: true
      run: aspire deploy
